### ISSUE TITLE
Issue of line break between each item

### ISSUE THREAD

**Issue by zklex** [claranet/ansible-role-sudo#6]
Issue of line break between each item, on template sudoer.j2

## Expected Behavior
```
sudo_rights:
  myuser:
    - name: "myuser"
      no_passwd: true
      from_hosts: ALL
      as_user: user2
      as_group: group2
      commands: ALL
      state: present
    - name: "myuser"
      no_passwd: true
      from_hosts: ALL
      as_user: user3
      as_group: group3
      commands: ALL
      state: present
```

Expected output : 

```
cat /etc/sudoers.d/myuser
## Ansible managed

myuserALL=(user2:group2) NOPASSWD: ALL
myuserALL=(user3:group3) NOPASSWD: ALL
```

Current output : 

```
cat /etc/sudoers.d/myuser
## Ansible managed

myuserALL=(user2:group2) NOPASSWD: ALLmyuserALL=(user3:group3) NOPASSWD: ALL
```
## Possible Solution

```diff
## {{ ansible_managed }}

{%+ for line in item.value -%}

{%- set _sudo_run_from_hosts = line.from_hosts | default('ALL') -%}
{%- set _sudo_run_as_user = line.as_user | default('ALL') -%}
{%- set _sudo_run_as_group = line.as_group | default('ALL') -%}
{%- set _sudo_use_nopasswd = 'NOPASSWD: ' if line.no_passwd | default(false) else ('') -%}
{%- set _sudo_run_commands = line.commands | default('ALL') -%}
{%- set _sudo_state_rights = line.state | default('present') -%}

{# extract command when we have one command set as a list #}
{%- if  _sudo_run_commands is iterable and _sudo_run_commands is not string -%}
    {%- if _sudo_run_commands|length > 1 %}
        {%- set _sudo_run_commands = _sudo_run_commands | join(',') -%}
    {%- else %}
        {%- set _sudo_run_commands = _sudo_run_commands[0] -%}
    {%- endif %}
{%- endif +%}
{%- if _sudo_state_rights == "present" -%}
    {{ line.name }} {{ _sudo_run_from_hosts }}=({{ _sudo_run_as_user }}:{{ _sudo_run_as_group }}) {{ _sudo_use_nopasswd }}{{ _sudo_run_commands }}
+ {% endif -%}
-  {-% endif -%}
{%- endfor -%}

```

## Your Environment

* Version used: 1.0.2
* Operating System and Ansible version: 

[Ubuntu 22.04.4 LTS](https://releases.ubuntu.com/jammy)

```
ansible --version
ansible [core 2.14.14]
  config file = None
  configured module search path = ['/home/zklex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zklex/.local/pipx/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/zklex/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/zklex/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/home/zklex/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.3
  libyaml = True
```
